.TH pdf-redact-tools 1 local
.SH NAME
pdf-redact-tools \- PDF Redact Tools helps with securely redacting and stripping

.SH SYNOPSIS
pdf-redact-tools [--help]
.SH DESCRIPTION
PDF Redact Tools helps with securely redacting and stripping metadata
from documents before publishing. It is self documented with the --help option.

.SH AUTHOR
Micah Lee <micah.lee@firstlook.org>
